// src/components/Canvas.vue
`<template>
  <div class="bg-gray-900 p-4 rounded-lg">
    <canvas ref="canvasRef"></canvas>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { fabric } from 'fabric';
import { useEditorStore } from '../stores/editor';

const canvasRef = ref<HTMLCanvasElement | null>(null);
const fabricCanvas = ref<fabric.Canvas | null>(null);
const store = useEditorStore();

onMounted(() => {
  if (canvasRef.value) {
    fabricCanvas.value = new fabric.Canvas(canvasRef.value, {
      width: 640,
      height: 360,
      backgroundColor: '#000'
    });
  }
});

onUnmounted(() => {
  fabricCanvas.value?.dispose();
});

watch(() => store.items, (items) => {
  if (!fabricCanvas.value) return;

  fabricCanvas.value.clear();
  
  items.forEach((item) => {
    if (item.type === 'text') {
      const text = new fabric.Text(item.content, {
        left: 100,
        top: 100,
        fill: 'white'
      });
      fabricCanvas.value?.add(text);
    }
  });

  fabricCanvas.value.renderAll();
}, { deep: true });
</script>`

// src/components/Canvas.tsx
import React, { useEffect, useRef } from 'react';
import { fabric } from 'fabric';
import { useEditorStore } from '../store/editorStore';

const Canvas: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const fabricRef = useRef<fabric.Canvas | null>(null);
  const items = useEditorStore((state) => state.items);

  useEffect(() => {
    if (canvasRef.current && !fabricRef.current) {
      fabricRef.current = new fabric.Canvas(canvasRef.current, {
        width: 640,
        height: 360,
        backgroundColor: '#000',
      });
    }

    return () => {
      if (fabricRef.current) {
        fabricRef.current.dispose();
        fabricRef.current = null;
      }
    };
  }, []);

  useEffect(() => {
    if (!fabricRef.current) return;

    fabricRef.current.clear();
    
    items.forEach((item) => {
      if (item.type === 'text') {
        const text = new fabric.Text(item.content, {
          left: 100,
          top: 100,
          fill: 'white',
        });
        fabricRef.current?.add(text);
      }
    });

    fabricRef.current.renderAll();
  }, [items]);

  return (
    <div className="bg-gray-900 p-4 rounded-lg">
      <canvas ref={canvasRef} />
    </div>
  );
};

export default Canvas;
